### ISSUE TITLE
somethins down

### ISSUE THREAD

**Issue by Jarvis110469** [nb5p/MyIP#9]
WebRTC
IPIP.net 
搜狐 + Moe IP
IP.SB
 ipify + ipapi
 is down please fix

**Comment by nb5p** [comment]
1. WebRTC 获取本机 IP 失败是浏览器隐私设置造成的，为正常现象。
2. 由于 IPIP.net 修改了 CORS 策略，仅靠前端页面无法解决。
3. 其余接口经测试，均正常工作。若无法使用，请先检查广告过滤相关插件是否对其进行了拦截。
